/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MetalRouteImport } from './routes/metal'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AcrylicRouteImport } from './routes/acrylic'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateIdRouteImport } from './routes/template.$id'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ProductLineIdRouteImport } from './routes/product.$line.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MetalRoute = MetalRouteImport.update({
  id: '/metal',
  path: '/metal',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AcrylicRoute = AcrylicRouteImport.update({
  id: '/acrylic',
  path: '/acrylic',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIdRoute = TemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const ProductLineIdRoute = ProductLineIdRouteImport.update({
  id: '/product/$line/$id',
  path: '/product/$line/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrylic': typeof AcrylicRoute
  '/b2b': typeof B2bRoute
  '/bulk': typeof BulkRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/merch': typeof MerchRoute
  '/metal': typeof MetalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/template/$id': typeof TemplateIdRoute
  '/product/$line/$id': typeof ProductLineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrylic': typeof AcrylicRoute
  '/b2b': typeof B2bRoute
  '/bulk': typeof BulkRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/merch': typeof MerchRoute
  '/metal': typeof MetalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/template/$id': typeof TemplateIdRoute
  '/product/$line/$id': typeof ProductLineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acrylic': typeof AcrylicRoute
  '/b2b': typeof B2bRoute
  '/bulk': typeof BulkRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/merch': typeof MerchRoute
  '/metal': typeof MetalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/template/$id': typeof TemplateIdRoute
  '/product/$line/$id': typeof ProductLineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acrylic'
    | '/b2b'
    | '/bulk'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/gallery'
    | '/merch'
    | '/metal'
    | '/sitemap.xml'
    | '/collections/$slug'
    | '/template/$id'
    | '/product/$line/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acrylic'
    | '/b2b'
    | '/bulk'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/gallery'
    | '/merch'
    | '/metal'
    | '/sitemap.xml'
    | '/collections/$slug'
    | '/template/$id'
    | '/product/$line/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acrylic'
    | '/b2b'
    | '/bulk'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/gallery'
    | '/merch'
    | '/metal'
    | '/sitemap.xml'
    | '/collections/$slug'
    | '/template/$id'
    | '/product/$line/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcrylicRoute: typeof AcrylicRoute
  B2bRoute: typeof B2bRoute
  BulkRoute: typeof BulkRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  MerchRoute: typeof MerchRoute
  MetalRoute: typeof MetalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplateIdRoute: typeof TemplateIdRoute
  ProductLineIdRoute: typeof ProductLineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metal': {
      id: '/metal'
      path: '/metal'
      fullPath: '/metal'
      preLoaderRoute: typeof MetalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acrylic': {
      id: '/acrylic'
      path: '/acrylic'
      fullPath: '/acrylic'
      preLoaderRoute: typeof AcrylicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$id': {
      id: '/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof TemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/product/$line/$id': {
      id: '/product/$line/$id'
      path: '/product/$line/$id'
      fullPath: '/product/$line/$id'
      preLoaderRoute: typeof ProductLineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcrylicRoute: AcrylicRoute,
  B2bRoute: B2bRoute,
  BulkRoute: BulkRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  MerchRoute: MerchRoute,
  MetalRoute: MetalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplateIdRoute: TemplateIdRoute,
  ProductLineIdRoute: ProductLineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
